swagger: "2.0"
info:
  title: sample-api
  description: Sample API
  version: 0.1.0
schemes:
  - https
produces:
  - application/json
paths:
  /:
    get:
      summary: summary
      operationId: sample
      x-google-backend:
        address: https://www.google.com/
      responses:
        "200":
          description: A successful response
          schema:
            type: string
